name: Container Scan - Super Mario

#on:
#  push:
#    branches:
#      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Build image locally
      - name: Build Docker Image
        run: |
          docker build -t supermario-app:latest .

      # 3. Scan image (FIXED)
      - name: Scan Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: supermario-app:latest
          format: table
          exit-code: '0'
          severity: 'CRITICAL,HIGH'